### ISSUE TITLE
Err in powershell

### ISSUE THREAD

**Issue by KiExitDispatcher** [KarbitsCode/hello-world#1]
```Write-Output "Hello World!"``` more formal way in powershell is  ```Write-Host "Hello, World!"..```

**Comment by KarbitsCode** [comment]
Is there a difference between `Write-Host` and `Write-Output`?

**Comment by KiExitDispatcher** [comment]
``Write-Host`` is used to display output directly to the console, while ``Write-Output`` sends objects down the pipeline for further processing.

**Comment by KarbitsCode** [comment]
Ok, I will push a commit to resolve this issue

**Comment by KiExitDispatcher** [comment]
oki doki
